### ISSUE TITLE
Release new version to Hex

### ISSUE THREAD

**Issue by mworrell** [saleyn/erlexec#103]
The newest version on Hex.pm dates from March 28, 2017.
Since then support for FreeBSD was added.

https://hex.pm/packages/erlexec

Could you please release a new version to Hex.pm?

We (@zotonic) received an issue report about not being able to build on FreeBSD

**Comment by saleyn** [comment]
Just got from vacation - will do this some time tomorrow.

**Comment by mworrell** [comment]
That is great news, thank you!

**Comment by saleyn** [comment]
Done

**Comment by mworrell** [comment]
Thanks for the very quick action!

I will update our dependencies.
