### ISSUE TITLE
Stopping the erlexec application results in shutdown_error

### ISSUE THREAD

**Issue by ruttenberg** [saleyn/erlexec#105]
_application:stop(erlexec)_

results in an error like this:
**[error] <0.239.0> Supervisor exec_app had child exec started with exec:start_link([]) at <0.240.0> exit with reason killed in context shutdown_error**

Is there a way to prevent this?

**Comment by saleyn** [comment]
This is a standard behavior by design - shutting down the system propagates the shutdown to all children.
Do you mean that you want the child process to keep on running if `erlexec` is shutdown?

**Comment by ruttenberg** [comment]
Propagating the shutdown to all children is not a problem. Is there a way to prevent the 'shutdown_error'?

**Comment by saleyn** [comment]
Is this still a problem?  If so, please provide steps to reproduce.

**Comment by ruttenberg** [comment]
The related project has been suspended for a while. I will close the issue and re-open when it becomes relevant again. Thanks.
