### ISSUE TITLE
Hex 1.7.4 published package contains x86_64 binaries

### ISSUE THREAD

**Issue by xadhoom** [saleyn/erlexec#107]
Right now the published package contains a priv/ dir with exec-port executable already in.

Should not be there, right?

here's a dir dump of a new checkout from hex.

> [foo@localhost erlexec]$ ls -R
> .:
> c_src  hex_metadata.config  include  LICENSE  priv  README.md  rebar.config  rebar.config.script  rebar.lock  src
> 
> ./c_src:
> ei++.cpp  ei++.hpp  exec.cpp  exec.hpp  exec_impl.cpp
> 
> ./include:
> exec.hrl
> 
> ./priv:
> x86_64-unknown-linux-gnu
> 
> ./priv/x86_64-unknown-linux-gnu:
> exec-port
> 
> ./src:
> edoc.css  erlexec.app.src  exec_app.erl  exec.erl  overview.edoc

**Comment by saleyn** [comment]
Republished a clean version.
