### ISSUE TITLE
erlexec not compiling with OTP 21 rc -1

### ISSUE THREAD

**Issue by pobengtsson** [saleyn/erlexec#108]
I have an erlang applicaiton that uses erlexec and when tried to build it https://github.com/erlang/otp/releases/tag/OTP-21.0-rc1 using rebar3 and erlexec 1.7.4, the compilation fails with error message:

erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

Could a fix be as easy as just removing the call to get_stacktrace?

**Comment by saleyn** [comment]
Since the version 21.0 is not yet officially released, I am hesitant to commit the fix yet, but it would involved ifdef'ing that line based on the distribution version to provide backward compatibility, since the new release contains different syntax for obtaining the stacktrace.

**Comment by pobengtsson** [comment]
Yes, I can understand your point of view. I'll revert to OTP-20 for the time being. Thanks for making erlexec and sharing it as open source.

**Comment by pdobacz** [comment]
Can we reopen the issue considering [21 release](https://www.erlang.org/news/123)?

**Comment by saleyn** [comment]
What is the issue?  Backward compatibility was addressed by [this PR](https://github.com/saleyn/erlexec/pull/117).

**Comment by pdobacz** [comment]
ah, my bad, didn't notice that PR. Thank you!
