### ISSUE TITLE
Does not compile after "Update for OTP release 21.0"

### ISSUE THREAD

**Issue by palimarrao** [saleyn/erlexec#110]
This might be at fault: https://github.com/saleyn/erlexec/commit/b4a4192692c895e3b19714fade20721041bfb381#diff-dadb34d095a4c6a877818436e0295d69

`===> Compiling src/exec.erl failed
src/exec.erl:668: illegal pattern
src/exec.erl:670: variable 'Reason' is unbound
src/exec.erl:670: variable 'StackTrace' is unbound
`

**Comment by saleyn** [comment]
Are you on the OTP 21 release?  If not, see the comment in the "Building" section of README.md.

**Comment by palimarrao** [comment]
D'oh. Works fine after upgrade to OTP 21.
