### ISSUE TITLE
Can't build for OTP 20

### ISSUE THREAD

**Issue by mkrentovskiy** [saleyn/erlexec#111]
Got rebar3 error:
===> Compiling _build/default/lib/erlexec/src/exec.erl failed
_build/default/lib/erlexec/src/exec.erl:668: illegal pattern
_build/default/lib/erlexec/src/exec.erl:670: variable 'Reason' is unbound
_build/default/lib/erlexec/src/exec.erl:670: variable 'StackTrace' is unbound

Fix it by replacing
        _:Reason:StackTrace ->
to
        Reason:StackTrace ->
at line 668.

**Comment by saleyn** [comment]
Please read the NOTE in the "Building" section of the README.md. Also see #110.
