### ISSUE TITLE
Scoped enums only available with -std=c++11

### ISSUE THREAD

**Issue by lpgauth** [saleyn/erlexec#115]
Hi, looks like https://github.com/saleyn/erlexec/commit/45b3fa77a41ea24e53b327d5fd141f4df5efccaa broke the build since scoped enums are only available in c++11.

https://travis-ci.org/rkallos/wrek/jobs/412903063#L452

**Comment by saleyn** [comment]
Not sure why I wasn't getting this problem with existing `rebar.config.script` that was including `-std=c++11`. This is fixed with your pull request removing redundant `-std=c++98`. Right?

**Comment by lpgauth** [comment]
Yup, it's fixed. Thanks for the fast merge 👍
