### ISSUE TITLE
escriptized app and 'Priv directory not available'

### ISSUE THREAD

**Issue by Darkkey** [saleyn/erlexec#122]
Looks like a reviving of '#92'. In case of using erlexec from escriptized app, even if `portexe` is set correctly via `exec:start([{portexe, ExecPortPath}])`, the library is still outputting a warning (however everything else in the lib works just fine):
```
=WARNING REPORT==== 11-Mar-2019::19:20:53.316687 ===
Priv directory not available
```
This is happening in `default()` when erlexec is running from escriptized application. Do erlexec explicitly require priv directory for any other reason than storing exec-port? Is it possible to make an option to suppress such warnings?

**Comment by saleyn** [comment]
The `priv` directory is not used for any other purpose than storing the port program. You are welcome to send a PR to suppress the warning if `ExecPortPath` is provided.

**Comment by Darkkey** [comment]
Please see #123

**Comment by Darkkey** [comment]
It seems working correct now, perfect, thank you!
