### ISSUE TITLE
Can't run command under root on Linux.

### ISSUE THREAD

**Issue by mkrentovskiy** [saleyn/erlexec#126]
I use erlexec for starting commands on small device (OpenWrt). Its must be started as root and there no other valid user which can be started it. But I have no luck to do it simple way, just switching off cap_mode in build command line.

Is this something method to do this without remove checks from Erlang and port code?

**Comment by saleyn** [comment]
Have you tried a test similar to "Allowing exec-port to run commands as other effective users" in [examples](http://saleyn.github.io/erlexec/overview-summary.html)?

**Comment by mkrentovskiy** [comment]
Yes, I try. 

If I add fake user like root - filters break on. With other users I can't start because its hasn't valid access rights.

Look like better use ports instead in this case. Thanks.
