### ISSUE TITLE
SHELL definition requirement is not per POSIX standard and is nonsensical

### ISSUE THREAD

**Issue by i1t** [saleyn/erlexec#131]
Why couldn't `erlexec` use `/bin/sh` and drop its requirement to specify `SHELL` environment variable???

POSIX standard doesn't require `SHELL` to be defined. One cannot expect this variable to be defined on all/most *nix systems.

**Comment by saleyn** [comment]
The "nonsensical" reason for relying on this variable is that I haven't seen a single *nix system that doesn't define the `SHELL` variable by default.

The POSIX standard certainly includes it:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html

Why is this problematic?
