### ISSUE TITLE
provide facility for unsetting environment variables

### ISSUE THREAD

**Issue by mk270** [saleyn/erlexec#133]
It's not clear (from some perusal of the C++ and docs) that there's any way of unsetting environment variables to prevent them being passed to the subprocess; I am trying to avoid polluting that environment / potentially exposing random variables which have been inherited by Erlang.

**Comment by saleyn** [comment]
The environment of a child process is inherited from the port process, which you can customize with the `{env, Env}` options: https://github.com/saleyn/erlexec/blob/master/src/exec.erl#L103.  This list can unset the variables you don't need.  But currently there's no option to clear all environment.

**Comment by mk270** [comment]
Yes, I'm aware of {env, Env}, but it's not clear how to use it to unset variables that are set in the port process. You can set them to the null string, but I don't see how to unset them, or to enumerate them.

**Comment by saleyn** [comment]
Enumerate by running the `exec:run("env", [{sync, stdout}])` command, and unset with `{env, [{"MYVAR", ""}]}`.

**Comment by mk270** [comment]
Ah, we're using different definitions of "unset" (I'd call `{env, [{"MYVAR", ""}]}` setting `MYVAR` to the null string rather than unsetting it.

Is there a way to avoid having a variable appear in the subprocess environment at all?

**Comment by saleyn** [comment]
Currently no.

**Comment by mk270** [comment]
Ok, well, I would like some mechanism and if I can write one in the next few months I shall send a Pull Request.

This is useful because it can protect against two real-world problems (neither of whichis particularly important, but we should not make it nearly impossible to fix them):

* the user runs the Erlang VM from the wrong startup script, and it inherits environment variables from, say, the shell, and passed them through to the erlexec port
* a program called by the erlexec port (e.g., a CGI script) for some reason distinguishes between an environment variable which is set and one which is set to the null string, and cannot be modified not to do this

**Comment by saleyn** [comment]
It seems that a proper solution would be to sanitize the environment prior to starting the Erlang VM, since other programs that are spawned from the Erlang OS process (such as the ones executed by `erlnag:open_port/2` or `os:cmd/1`) still inherit VM's environment.

There's an easy way to clear environment in a shell by prefixing your command with `env -i`:
```
exec:run(["/usr/bin/env", "-", "/usr/bin/env"], [sync, stdout]).
```

**Comment by saleyn** [comment]
This feature is implemented in the latest commit.  Use `{env, [clear]}` option to clear all environment, and `{env, [{"VAR", false}]}` to unset a variable.

**Comment by mk270** [comment]
Thank you very much indeed. I shall check this out, but by your description I believe it solves the two problems I'm actually dealing with.
