### ISSUE TITLE
Summary of changes from 1.10.9 to 1.16.4?

### ISSUE THREAD

**Issue by axelson** [saleyn/erlexec#134]
Is it possible to get a summary of the changes from 1.10.9 to 1.16.4? It looks like https://github.com/saleyn/erlexec/issues/127 is one fix, and another is OpenBSD support. Are there any other major fixes or improvements?

**Comment by saleyn** [comment]
Added support for accepting binary commands (mainly to help Elixir users). The bump in version is due to continuous errors with the rebar3, which were reported and resolved by rebar3 support.

**Comment by axelson** [comment]
Okay that makes sense. Switching to binaries will definitely make it more ergonomic to use. Thanks!
