### ISSUE TITLE
Establishing/Supervising Communications With a Long-Running, Data Streaming Python Process

### ISSUE THREAD

**Issue by Maxximiliann** [saleyn/erlexec#146]
Ubuntu 20.04.1 LTS
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)

Our Elixir project requires initiating and then supervising communications with a long-running, data streaming Python process. Data will be pushed to its Elixir counterpart once every second. Both processes are running on the same machine.

Is your library ideally suited for this? If so, where can we find recipes for such a use case?

**Comment by saleyn** [comment]
If the amount of data sent to Elixir by that process is small, then yes.  All I/O of child processes sent to Elixir is funneled through `exec-port` executable.

**Comment by Maxximiliann** [comment]
Small? Where are the basic size limitations explained in the docs?

**Comment by saleyn** [comment]
There is no hard limitation - you just need to try and see if the amount of data your process is producing doesn't cause too high CPU utilization in `exec-port`.  So far no one observed that being an issue.
