### ISSUE TITLE
New release? Resolve port hanging

### ISSUE THREAD

**Issue by ewildgoose** [saleyn/erlexec#147]
Hi, there is an interesting commit on Jan 9th about resolving a port hang. I have been experiencing situations where I have lots of exec-port processes hanging around after running my project. First impressions are that switching to git version resolves this.

Could you consider making a new release with this fix in it?

(debugging: Projects in elixir and running on osx + linux. Using the exexec wrapper to execute both run/run_link functions)

Thanks for erlexec!

**Comment by saleyn** [comment]
I published the current master's HEAD to `hex`. Does this solve your issue?

**Comment by ewildgoose** [comment]
Perfect! Many thanks!
