### ISSUE TITLE
I am running into issues with elixir release

### ISSUE THREAD

**Issue by tiagodavi** [saleyn/erlexec#156]
erlang 24.1.7
elixir 1.13.1
Running on docker arm32v7/elixir:1.13

If I run: `iex -S mix ` erlexec works fine

If I run `mix release` I have this error below when app is started:
` ** (UndefinedFunctionError) function :exec.start/1 is undefined (module :exec is not available)`

Does anyone know how can I solve this?

**Comment by saleyn** [comment]
Did you install erlexec or included it as the dependency in your project as per installation instructions?

**Comment by tiagodavi** [comment]
I included it as dependency

**Comment by saleyn** [comment]
You haven't provided any details about your OS, whether you tried to clone and compile erlexec separately from your project.  Please do so first, and if it builds, the issue is elsewhere in your project's configuration.
