### ISSUE TITLE
Any command terminates with exit status 132

### ISSUE THREAD

**Issue by Zabrane** [saleyn/erlexec#176]
Hi @saleyn 

We are using `erlexec` from this commit `7b58687a6fc7b750a49c0a64d9753c97512570d1`.
Our Erlang release runs perfectly inside Docker. Today, we deployed a new version of our app and start getting `erlexec` errors.  Any command we try to run ends up with the same exit status `132`.

Here is an example from with `Docker`:
```erlang
$ /opt/arben/bin/arben remote_console
> f(I), f(P), {ok, P, I} = exec:run("echo ok", [{stdout, self()}, monitor]).
** exception exit: {{exit_status,132},
                    {gen_server,call,
                                [exec,
                                 {port,{{run,"echo ok",[{stdout,<0.2244.0>},monitor]},
                                        monitor,false}},
                                 30000]}}
     in function  gen_server:call/3 (gen_server.erl, line 419)
     in call from exec:do_run/3 (/dev/arben/_build/default/lib/erlexec/src/exec.erl, line 970)
```

1. What make `erlexec` terminates with exit code `132`?
2. Would you recommend using `erlexec` from `master` ?

This only start happening today. Before deploying our new release, `erlexec` was working as expected.

Help appreciated

**Comment by Zabrane** [comment]
@saleyn same error when trying the latest `erlexec` from master.

**Comment by Zabrane** [comment]
@saleyn I think we found the issue:
https://github.com/saleyn/erlexec/blob/master/c_src/Makefile#L72-L77

You've added `AVX/AVX2` compilation flags, and our target Docker machine doesn't support them.
After recompiling `erlexec` without these flags, it worked.

**Question**: why these `AVX/AVX2` flags ? Do you really need `SIMD` instructions inside `erlexec`?

Keep you posted.

**Comment by saleyn** [comment]
This was an optimization to vectorize loops.  I can take it out for compatibility.

**Comment by saleyn** [comment]
Please check the master branch now.

**Comment by saleyn** [comment]
BTW, this is how you can check the meaning of a status code:
```erlang
1> exec:status(132).
{signal,sigill,true}
```

**Comment by Zabrane** [comment]
> BTW, this is how you can check the meaning of a status code:
> 
> ```erlang
> 1> exec:status(132).
> {signal,sigill,true}
> ```

Forget that one, thanks.

**Comment by Zabrane** [comment]
> This was an optimization to vectorize loops. I can take it out for compatibility.

Yes please, take it off. We heavily rely on `erlexec` for many years.

**Comment by Zabrane** [comment]
> Please check the master branch now.

Working as expected now. Many thanks.
