### ISSUE TITLE
`debug(1)` impacts stdout of a command

### ISSUE THREAD

**Issue by kape1395** [saleyn/erlexec#181]
While debugging #180 I found that some logging statements appear in the program's stdout instead of being logged (I have omitted the logged statements to make this more readable).
```erlang
28> exec:debug(0).                                                  
29> exec:run_link("/usr/bin/echo asd", [sync, stdout, stderr, pty]).
{ok,[{stdout,[<<"asd\r\n">>]}]}

30> exec:debug(1).                                                  
31> exec:run_link("/usr/bin/echo asd", [sync, stdout, stderr, pty]).
{ok,[{stdout,[<<"TIOCSWINSZ rows=43430 cols=23527 tty=-1 ret=-1 [exec_impl.cpp:186]\r\r\nTIOCSWINSZ rows=1974839"...>>,
              <<"asd\r\n">>]}]}
```

Also, if the `pty` option is specified, stderr is returned as stdout:
```erlang
49> exec:run_link("/usr/bin/echo asd; (/usr/bin/echo dsa >&2)", [sync, stdout, stderr]).     
{ok,[{stdout,[<<"asd\n">>]},{stderr,[<<"dsa\n">>]}]}
50> exec:run_link("/usr/bin/echo asd; (/usr/bin/echo dsa >&2)", [sync, stdout, stderr, pty]).
{ok,[{stdout,[<<"asd\r\n">>,<<"dsa\r\n">>]}]}
```

In my case that's minor, as the pty option was specified by a mistake.

**Comment by saleyn** [comment]
With `pty` the stderr is returned to stdout.  This is not a but in `erlexec` but a limitation of the `pty` option related to the the [tty's behavior](https://github.com/saleyn/erlexec/issues/41).
