### ISSUE TITLE
Does not compile when project directory contains spaces

### ISSUE THREAD

**Issue by knightpp** [saleyn/erlexec#184]
How to reproduce:
```shell
mkdir -p "~/folder with spaces/"
cd "~/folder with spaces/"
mix new repr
# Add {:erlexec, "~> 2.0"} to mix.exs
mix deps.get
mix deps.compile
```
And in the output will be something like this
```
Makefile:127: target '/run/host/...' given more than once in the same rule
Makefile:127: target 'and' given more than once in the same rule
Makefile:131: target '/run/host/...' given more than once in the same rule
Makefile:131: target './' given more than once in the same rule
```

**Comment by saleyn** [comment]
This is the general bug/problem with the `make` tool.  See [this](https://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces). I will close this issue as it's beyond `erlexec` project, unless the some other way of building the C++ program is used other than the make tool.
