### ISSUE TITLE
Could we have an option to send a different signal to external process

### ISSUE THREAD

**Issue by zugolosian** [saleyn/erlexec#49]
It would be nice if we could issues a SIGINT, then a SIGTERM and then a SIGKILL so our python processes can clean up their resources nicely. Or alternatively just choose the signal we send before sending the SIGKILL.

{kill_timeout, Sec::integer()}
Number of seconds to wait after issueing a SIGTERM or executing the custom kill command (if specified) before killing the process with the SIGKILL signal

**Comment by saleyn** [comment]
You can use custom `{kill, KillCmd}`, where KillCmd is `"kill -INT YourPid && sleep 5 && kill -TERM YourPid && sleep 5 && kill -9 YourPid"`

**Comment by zugolosian** [comment]
Yeah I saw that as an option, but it would be a lot nicer to send signals rather than starting an external shell command if possible.

**Comment by saleyn** [comment]
You can accomplish that with setting `{kill_timeout, N}` long enough the give your process a chance to cleanup on SIGTERM, which will be sent automatically first prior to doing a "hard" kill with SIGKILL. The fact that you require SIGINT is not a generic behavior for the majority of standard tools.

**Comment by zugolosian** [comment]
It looks like we could just manage an external process and then use kill(ospid, signal). If the managed process doesn't die within a timeout then we'll use stop which should cover what we need. I didn't realize you could send signals directly. Thanks!
