### ISSUE TITLE
Exit code mismatch

### ISSUE THREAD

**Issue by eproxus** [saleyn/erlexec#50]
Running erlexec with `monitor` as an option, I receive `{'DOWN', #Ref<0.0.0.3303>, process, <0.207.0>, {exit_status, 256}}`, however running the command in the shell returns the error code `1`.

The command is started with:
```erl
exec:run(["/path/to/command", "--id", "1", "--control", ":3333"], [monitor, {stdout, print}, {stderr, print}, {kill_timeout, 1}])
```

The output and message received is:
```erl
Got stderr from 66903: <<"time=\"2015-07-16T16:18:53+02:00\" level=fatal msg=\"Could not create controller: dial tcp 127.0.0.1:23000: connection refused\" \n">>
{'DOWN', #Ref<0.0.0.3303>, process, <0.207.0>, {exit_status, 256}}
```

However, running the command in the shell shows the error code is actually `1`:
```sh
$ /path/to/command --id 1 --control :3333
FATA[0000] Could not create controller: dial tcp :3333: connection refused
$ echo $?
1
```

**Comment by saleyn** [comment]
You need to use the exec:status/1 call to interpret the exit code:

2> exec:status(256).
{status,1}

**Comment by eproxus** [comment]
Excuse my lack of knowledge, on the subject, but why? :smile: What's the difference between `status` and `status` in these contexts?

**Comment by saleyn** [comment]
The exit code returned by Linux and other OS's that support signals contains information on how the process was terminated (normally or by signal), so the value returned in `{exit_status, N}` needs to be interpreted by the `exec:status/1` call to get the "real" exit status.

**Comment by eproxus** [comment]
I see, thanks!
