### ISSUE TITLE
manage links with fake OS pid without an error

### ISSUE THREAD

**Issue by Timrael** [saleyn/erlexec#51]
Hello Sergei,

I have an issue with passing fake OS pid to manage function:

```erlang
FakeOsPid = 12345.
exec:manage(FakeOsPid, []).
```

I expect 'error', but always got 'ok'.

**Comment by saleyn** [comment]
This issue has been fixed in the latest commit.

**Comment by Timrael** [comment]
Thanks! You're doing a good job.

**Comment by Timrael** [comment]
@saleyn sorry man, but now exec:manage returns {error, not_found} for all pids, no matter it's real or not.

**Comment by saleyn** [comment]
I can't reproduce your issue:
```
$ sleep 2000
$ ps aux | grep sleep
serge    12834  0.0  0.0   5800   760 pts/3    S+   17:00   0:00 sleep 2000
$ erl
$ exec:start().
{ok,<0.36.0>}
2> exec:manage(12834, []).
{ok,<0.38.0>,12834}
```

**Comment by saleyn** [comment]
Apparently the Linux API call I used wasn't correct. The issue is fixed now.
