### ISSUE TITLE
Redirecting shell arguments to temp file

### ISSUE THREAD

**Issue by Immortalin** [saleyn/erlexec#57]
Assuming a program called foo which takes a file as an argument, how do I do something like this e.g. in bash I could redirect an argument's contents into a temp file with something like `foo <(echo "hello world") `. Is there a way to do something similar in pure Erlang without having to shell out to bash?

**Comment by saleyn** [comment]
See http://saleyn.github.io/erlexec/ "Redirecting OS process stdout" section.

You can also redirect stdin, by passing `{stdin, Filename::string}` option.
