### ISSUE TITLE
Sync run fails when mailbox is non empty

### ISSUE THREAD

**Issue by egobrain** [saleyn/erlexec#58]
Sync run always fails with non empty process mailbox box due to [this](https://github.com/saleyn/erlexec/blob/master/src/exec.erl#L724) piece of code.

Example

```erlang
1> exec:run("ls", [sync]).
{ok,[]}
2> self() ! test.         
test
3> exec:run("ls", [sync]).
{error,[{reason,test}]}
```

**Comment by saleyn** [comment]
Thanks. Fixed in latest commit.
