### ISSUE TITLE
Exit status shifted 8 bits?

### ISSUE THREAD

**Issue by gar1t** [saleyn/erlexec#60]
This is surprising to me:

```erlang
30> exec:run_link("sleep 1; exit 1", []).                   
{ok,<0.118.0>,20435}
** exception error: {exit_status,256}
31> exec:run_link("sleep 1; exit 2", []).
{ok,<0.121.0>,20437}
** exception error: {exit_status,512}
```

Why is the reported exit status shifted 8 bits?

**Comment by saleyn** [comment]
Use the [exec:status/1](http://saleyn.github.io/erlexec/exec.html#status-1) to decode the status, which is in usual POSIX format.

**Comment by gar1t** [comment]
I see - okay, thanks!
