### ISSUE TITLE
Port crash if cmdline length is equal 265 bytes.

### ISSUE THREAD

**Issue by mkrentovskiy** [saleyn/erlexec#64]
I got port crash when command line length is equal 256 bytes (255 or 257 working fine). Look like some allocation problem. Cmd params was just [sync].

Error: glibc detected *** /app/deps/erlexec/priv/x86_64-unknown-linux-gnu/exec-port: double free or corruption (out): 0x00007fffe535ef00

**Comment by saleyn** [comment]
Thanks for reporting. Please check the master branch for a fix.
