### ISSUE TITLE
Crash while calling `exec:stop_and_wait(I, 5000)`

### ISSUE THREAD

**Issue by jlouis** [saleyn/erlexec#68]
## Symptom:

In my code I have a call to

    exec:stop_and_wait(I, 5000),

This crashes with an error `{badmatch, []}` when called, because of this match in `exec`:

https://github.com/saleyn/erlexec/blob/576fb5d9b092c3e8bc40dbcae6daec52921c91a3/src/exec.erl#L396

## Expected output:

I would probably have expected the code to return an error term, something like `{error, not_found}` in this case. The mon referenced by `I` is gone when the call is made, but I'm doing it to clean up in the case it is not dead yet.

## Question:

Is this intended behavior or an error? Am I using the API incorrectly?

**Comment by saleyn** [comment]
Yes, this is reasonable. Fixed in the latest commit in the master.
