### ISSUE TITLE
test.cpp should not be included in compilation of exec-port

### ISSUE THREAD

**Issue by antipax** [saleyn/erlexec#69]
Hi,

I'm running into some issues with compiling v1.1.1 of erlexec from hex.pm for x86_64-alpine-linux-musl. Specifically, it appears that the test.cpp file is included in the compilation process even though it should not be (defines a second main, has `#include <ei++.hpp>` at the top which causes compilation to fail, etc.). Should this file be removed, or excluded from compilation somehow? I'm on 1.1.0 for now which is fine, but would like to upgrade to v1.1.1.

Thanks!

**Comment by antipax** [comment]
Looks like that file is actually not in this repository, so maybe the package just needs to be updated on hex.pm with the clean contents of this repository?

**Comment by saleyn** [comment]
I just synch'd the hex's repository. Please check again.

**Comment by antipax** [comment]
Works perfectly now. Thanks so much for the quick response!
