### ISSUE TITLE
`mix deps.compile` fails on Mac OSX El Capitan + HomeBrew

### ISSUE THREAD

**Issue by jvantuyl** [saleyn/erlexec#71]
Not sure what's behind this.  It appears the the `-m64` option to `g++` is what's breaking it.  The errors I get are:

```
ld: warning: ld: warning: ignoring file c_src/exec.o, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): c_src/exec.oignoring file c_src/ei++.o, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): c_src/ei++.o

Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Removing the `-m64` from the build seems to have fixed it.  I'm not sure if this is the right way to do it, but you can see a working build at jvantuyl/erlexec@ffa8bc25594c8133b72fa7ba1cd686562850a721.

**Comment by saleyn** [comment]
Do you have a 32bit or 64bit platform?

**Comment by jvantuyl** [comment]
64-bit.

**Comment by saleyn** [comment]
Could you send a PR with your fix?  Unfortunately I don't have Mac OS / Darwin environment to validate this, but if it breaks the build for other users, they'll let us know.

**Comment by saleyn** [comment]
Are you still having this build error with the current master branch?
