### ISSUE TITLE
c_src/*.d files present in hex package

### ISSUE THREAD

**Issue by antipax** [saleyn/erlexec#72]
Hi @saleyn!

Thanks for the great library. Building via hex dep on OS X is failing currently, because 2 files are present in the c_src dir in the hex package: `ei++.d` and `exec.d`. After deleting these files, the build works perfectly. Could you bump the version and publish to hex without those two files?

Thanks!

**Comment by saleyn** [comment]
Unfortunately I am not sure if rebar3 has an option to exclude certain files from the hex package. If you know how to do that, please push a PR.

**Comment by antipax** [comment]
@saleyn I'm not sure that there is, but currently the package is broken. You could do "rm -rf `git ls-files --others`" to clean the repository before publishing, seems like *.d is already in your .gitignore?

**Comment by saleyn** [comment]
Does a hex package store just the "clean" source code of a project, or it needs to have some other artifacts, such as the the *.beam files?

**Comment by antipax** [comment]
Just the source code is needed.

**Comment by saleyn** [comment]
Getting an error publishing this package to hex. Filed a rebar3 issue https://github.com/erlang/rebar3/issues/1203.

**Comment by saleyn** [comment]
Published the clean version to hex.
