### ISSUE TITLE
Including erlexec as a dependency fails

### ISSUE THREAD

**Issue by eazar001** [saleyn/erlexec#79]
Trying to include `{erlexec, "1.2.1"}` as a dependency via rebar3 fails with an uncaught error in rebar_core.

From the crash dump:

```
Error: {badmatch,{error,{35,file,
                         {error,{badmatch,{error,enoent}},
                                [{erl_eval,expr,3,[]}]}}}}
```

**Comment by saleyn** [comment]
Does it work for you when using a spelled out dependency descriptor:
```
{erlexec, ".*", "https://github.com/saleyn/erlexec.git", {branch, "1.2.1"}}}
```

**Comment by eazar001** [comment]
When including,
```
{erlexec, ".*", {git, "https://github.com/saleyn/erlexec.git", {branch, "1.2.1"}}}
```
in the deps section of my `rebar.config`, I still get the same error unfortunately. If I try your method above exactly I get a naming error.

**Comment by saleyn** [comment]
You'd need to troubleshoot your rebar3 installation.  This doesn't seem to be related to this project.

**Comment by eazar001** [comment]
Perhaps not, but I was able to include 4 other separate dependencies without issue before `erlexec`.

I will take a closer look at other possible causes for this issue before reporting back.

**Comment by eazar001** [comment]
I filed and issue with `rebar3` to see if anyone recognizes a problem with the core.

**Comment by eazar001** [comment]
There was something very fishy going on with my project release. I was able to verify this by initializing a dummy project and verifying that the dep include worked there. I cannot isolate what I did wrong, but at least now I know the fault neither lies with my rebar3 installation nor with erlexec.
