### ISSUE TITLE
Zero length arguments considered invalid

### ISSUE THREAD

**Issue by gar1t** [saleyn/erlexec#81]
```
> exec:run(["/bin/echo", ""], [sync, stdout]).
{error,"badarg: invalid command argument #1"}
```

Looking at ei++.hpp decodeString the change wasn't obvious to me.

**Comment by saleyn** [comment]
Why are you using this syntax as opposed to any one of the following?
```
2> exec:run("/bin/echo", [sync, stdout]).
{ok,[{stdout,[<<"\n">>]}]}
3> exec:run(["/bin/echo"], [sync, stdout]).
{ok,[{stdout,[<<"\n">>]}]}
```

**Comment by gar1t** [comment]
This is just an example to highlight the behavior - my goal here isn't to echo chars :)

A zero length argument is a valid argument and this behavior prohibits their use.

**Comment by gar1t** [comment]
It's admittedly not a common case, but there are times when you may want to indicate that a particular argument exists positionally but is empty.

**Comment by saleyn** [comment]
I pushed a fix that takes care of it.

**Comment by gar1t** [comment]
Terrific - thanks!
