### ISSUE TITLE
Unable to find the exec-port binary

### ISSUE THREAD

**Issue by zackehh** [saleyn/erlexec#82]
I'm running builds on Travis CI and erlexec is compiling `x86_64-linux-gnu-gnu`, but the runtime is trying to read `x86_64-unknown-linux-gnu`. 

Is it possible to make reading of the binary resilient to errors like this? E.g. there should only ever be a single binary, so you could just list the directory and pull the first one.

**Comment by saleyn** [comment]
The reason the binary port program is put into the architecture-specific directory is that some installations prefer to have a shared repository of libs (e.g. on NFS) that is accessed by multiple machines in local network with different architectures.

Additionally, it seems that this particular problem is caused by the changes introduced by the pull request https://github.com/saleyn/erlexec/pull/63, so maybe @rstreif could make an adjustment based on this, so that this fix doesn't break the cross-environment support?

**Comment by zackehh** [comment]
@saleyn it is indeed reported as x86_64-unknown-linux-gnu but somehow the compilation didn't use that. Can't the compiler compile to `erlang:system_info(system_architecture)` as well?

**Comment by saleyn** [comment]
It does (see https://github.com/saleyn/erlexec/blob/master/src/exec.erl#L534), unless you override it with the `portexe` application option.

**Comment by zackehh** [comment]
@saleyn I don't really know how to fix the issue without simply reverting that PR. It seems that the change is assuming you're running on a different system to the one you're building on, and introduces some flaky(?) logic.

It seems to make sense to simply keep using `erlang:system_info(system_architecture)` with the assumption that you're compiling on the system you're going to run on, because that would guarantee that they're in sync.

@rstreif any ideas on a middle ground between your changes and what was there before?

**Comment by zackehh** [comment]
@saleyn would you be open for the run-time call to do a lookup to figure out what the parent dir of `exec-port` is? So at run-time it doesn't care what it was called, it just figures out the name automatically. Not sure if that would cause an issue?

**Comment by saleyn** [comment]
I am certainly open to idea of modifying the default: https://github.com/saleyn/erlexec/blob/master/src/exec.erl#L533, so that if it doesn't find `exec-port` at that location, it would search elsewhere.  However the preference would be to synchronize the compilation/run-time to some common ground.  Perhaps instead of using `<arch>-<vendor>-linux-gnu`, switch to `<arch>-<vendor>`?

**Comment by zackehh** [comment]
@saleyn if that's the case then I'd suggest simply doing a search and having that be the only behaviour - I don't think there's a good way to detect all cases otherwise :(

**Comment by saleyn** [comment]
That was the original behavior prior to @rstreif's PR.  Let's wait for him to reply, as reverting that PR would break compatibility with his deployment.

**Comment by rstreif** [comment]
Sorry for the delayed response. I am traveling.

@zackehh What is the environment you are compiling in?

- What is the OS/Linux distro you are running your Travis CI on?
- What is the compiler you are using and what is the output of compiler -dumpmachine? I suspects it's x86_64-linux-gnu.
- Apparently the environment variable CXX is set. Is it containing the compiler you are using in your CI?

`erlang:system_info(system_architecture)` does not work when cross-building as the Erlang runtime is the one of the host and not of the target. In that case the compiler correctly reports the target  The old behavior using `erlang:system_info(system_architecture)` is still there and used if the `CXX` environment variable is not set. In  your case it is set to a compiler but that compiler is not reporting the vendor string. The fix would be to tokenize `Target`, see if the second element in the list is `linux' in which case the vendor string is missing, and then insert 'unknown'.

**Comment by zackehh** [comment]
@rstreif it's the default Ubuntu image, I dunno if that's handrolled or something.

In addition, this lib is now broken on the latest OS X as `x86_64-apple-darwin15.5.0` is generated, but it tries to load `x86_64-apple-darwin16.0.0`.

I still believe that doing a search is the better option, it's far more resistant to change.

**Comment by zackehh** [comment]
Here is my proposed fix: https://github.com/saleyn/erlexec/pull/86

Verified that it finds the port correctly, even when the arch lookup is generating the wrong name. If someone could take a look over it, I'd appreciate it.
