### ISSUE TITLE
Exec-port binary can't be found when erlexec is distributed in a release

### ISSUE THREAD

**Issue by ccrusius** [saleyn/erlexec#84]
If `erlexec` is packaged as an application using reltool, `exec-port` will not be found. This is due to the `.beam` files being put into an archive. The error message says it all:

sh: line 0: exec: /Users/ccrusius/git/spoken-code/build/erlang/rel/lib/erlexec-1.2.2.ez/erlexec-1.2.2/priv/x86_64-apple-darwin15.5.0/exec-port: cannot execute: Not a directory

This is also mentioned [here](http://erlang.org/pipermail/erlang-questions/2011-October/062026.html).

I will be providing a fix soon.

**Comment by saleyn** [comment]
Please submit a PR.

**Comment by ccrusius** [comment]
Submitted (request #85)
