### ISSUE TITLE
Warn about missing SHELL environment variable

### ISSUE THREAD

**Issue by teamon** [saleyn/erlexec#88]
When running inside docker container using e.g. alpine-erlang base image one may encounter `{:error, [exit_status: 256, stderr: ["Pid 65: cannot execute '(null)': Bad address\n"]]}` error. 
This is caused by missing `SHELL` ENV variable - setting it to e.g. `SHELL=/bin/sh` solves this issue.

I wonder if it could be possible to add some kind of check/warning or is it out of scope of erlexec?

**Comment by saleyn** [comment]
Implemented this check in master.
