### ISSUE TITLE
hex.pm packaged 1.6.4 contains x86_64 object files

### ISSUE THREAD

**Issue by kennethlakin** [saleyn/erlexec#96]
The erlexec package that was pushed to hex.pm contains x86_64 object files (in addition to some relatively harmless .d files) in the `c_src` directory. These pre-built object files fail to link on systems that aren't x86_64.

When you get a moment, could you clean out the .o and .d files from the `c_src` directory and push an update to Hex? Thanks in advance.

**Comment by saleyn** [comment]
Thanks for reporting. I am on vacation now, will republish after Mar 10th.

**Comment by saleyn** [comment]
See commit cc338b79
