### ISSUE TITLE
Can't compile c lib on OS X

### ISSUE THREAD

**Issue by joefiorini** [saleyn/erlexec#98]
I'm trying to build `erlexec` on OS X and I'm getting:

```
===> /Volumes/Shared/src/process_spike/deps/erlexec/c_src/exec_impl.cpp:318:10: error: use of undeclared identifier 'ptsname_r'; did you mean 'ttyname_r'?
            r = ptsname_r(fdm, pts_name, sizeof(pts_name));
                ^~~~~~~~~
                ttyname_r
/usr/include/unistd.h:488:6: note: 'ttyname_r' declared here
int      ttyname_r(int, char *, size_t) __DARWIN_ALIAS(ttyname_r);
         ^
1 error generated.
```

I believe this is due to #95 which it appears introduced the call to `ptsname_r`. This function does not exist on OS X.

**Comment by jlouis** [comment]
We are also being hit by this one, on OSX. Same build error. I would wish I could "star" this task and say "me too", but the 👍 doesn't really connotate that expression I think. It isn't a thumbs-up I'm giving, it is a :me too: ...

**Comment by saleyn** [comment]
Looks like Mac OS X has a different signature of this function.  I don't have a Mac environment to test this on.  Could either one of you try the following ifdef'd approach and see if it works in erlexec?
https://github.com/st3fan/osx-10.9/blob/master/Libc-997.1.1/gen/utmpx-darwin.c#L403

**Comment by jlouis** [comment]
Hi!

I can confirm that your patch solves the compile part of the problem, at the very least. It probably also works, but I have only done some rudimentary test of erlexec in general, as I do not know where that piece of code is being used and thus trigger an example where I'm sure I walk that code path and get coverage.
